### ISSUE TITLE
Feature Request: Improve error display during generate command

### ISSUE THREAD

**Issue by brunosmm** [fauna-brecht/fauna-schema-migrate#13]
### Problem
During `generate` command if has an error on the FQL/JS only shows the FQL problem but does not indicate in which file the problem happens, if you have several changes may be difficult to find which one has the problem.
![image](https://user-images.githubusercontent.com/1554850/109398359-4db94f00-791b-11eb-9f71-2b7469b12012.png)

### Request
Add the File from the resource folder who has the problem.

**Comment by fauna-brecht** [comment]
Done 0.1.12
