### ISSUE TITLE
Document FAUNADB_PORT env variable

### ISSUE THREAD

**Issue by gmencz** [fauna-brecht/fauna-schema-migrate#14]
As I was setting up this tool with a local Docker fauna image, it kept trying to connect to an instance running on port 127.0.0.1:80 and I looked into the source code and realized that you can specify the port to use via `FAUNADB_PORT`, this should be documented since it's needed for Docker environments.

**Comment by fauna-brecht** [comment]
Thanks, that's good feedback. Will change asap and sorry for the inconvenience :)
