### ISSUE TITLE
"node_modules/fauna-schema-migrate/ink-select-input@github:fauna-brecht/ink-select-input" does not contain a package.json

### ISSUE THREAD

**Issue by gsears** [fauna-brecht/fauna-schema-migrate#25]
Again, many thanks for a great tool.

Recently our BB pipeline (for running migrations before tests with a fresh install) started throwing this on `npm install` :

```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/fauna-schema-migrate/ink-select-input@github:fauna-brecht/ink-select-input" as it does not contain a package.json file.
```

Deleting node_modules locally and running `npm install` produced the same error. However, reverting the `fauna-schema-migrate` version in `package.json` to v2.0.0 rather than 2.1.0 seemed to fix.

Feel free to let me know if I'm missing something, but I'm guessing it's something to do with referencing your forked repo perhaps?

Cheers!

**Comment by fauna-brecht** [comment]
to get more information, did you delete package.json.lock as well?

**Comment by gsears** [comment]
Deleting package.json.lock and reinstalling did it.

Thanks!
