### ISSUE TITLE
Feature Request: Force exit erros when migrations cannot run

### ISSUE THREAD

**Issue by brunosmm** [fauna-brecht/fauna-schema-migrate#3]
First thanks for this lib! Making my life much easier to maintain my schema!

I current use if integrate with my code and CI/CD pipeline, and would be really helpful if you add an option to force throw an error to the shell, this will help to identify migration problems and stop the CI/CD pipeline. Current if an errors happens cannot be identified by the pipeline and it continues executing.

Example:
![image](https://user-images.githubusercontent.com/1554850/107881102-7b38de00-6ec1-11eb-8aea-0542b34fde91.png)

How this step is configured in my pipeline:

` node_modules/.bin/fauna-schema-migrate apply all -k FAUNA_ADMIN_KEY`

How I workaround it:
```
 FAUNA_SETUP=$(node_modules/.bin/fauna-schema-migrate apply all -k << parameters.fauna-secret >> -n)
            echo "$FAUNA_SETUP"
            if [[ ${FAUNA_SETUP} == *"Error"* ]]; then
              exit 2
            fi
```
How it could be:

` node_modules/.bin/fauna-schema-migrate apply all -k FAUNA_ADMIN_KEY --throw-errors`

This will give an exit on the shell like 127 which would fail this step in the pipeline.

**Comment by fauna-brecht** [comment]
The package which I pushed for the windows issues 
https://www.npmjs.com/package/@fauna-databrecht/staging-fauna-schema-migrate
contains adaptions that make more sense. The behaviour is:

run will remain interactive
other actions besides run will exit on error.
Does that help?

**Comment by fauna-brecht** [comment]
Closing since the issue was addressed. If it did not solve your problem, feel free to reopen.
