### ISSUE TITLE
Socket hang up on bigger payloads

### ISSUE THREAD

**Issue by stefanhar** [fauna-brecht/fauna-schema-migrate#5]
Get an error when submitting a "big" migration.

Error: `FetchError: request to https://db.fauna.com:443/ failed, reason: socket hang up`

On a 653 line migration query ~10778 letters (collections: 7, indexes: 12: roles: 5).
Goes through when I split this into two migrations and run each with `yarn fauna-schema-migrate apply`.
This still fails with the same error when multiple migrations are run with `yarn fauna-schema-migrate apply all`.

**Comment by fauna-brecht** [comment]
Hey @stefanhar, thanks. I have noticed the same and I think (but might be wrong) this might be related to a node-fetch problem with our driver. This might be related https://github.com/fauna-brecht/fauna-schema-migrate/issues/5.
I have opened an internal ticket around this and we are looking into it.

**Comment by fauna-brecht** [comment]
in the meantime a new fauna js driver has been released which fixes this issue. 
The issue can also be solved for people who are still using the old driver by setting keep alive to false. I changed this in the the fauna-schema-migrate library to make sure that people who haven't seen this and are working with an older javascript driver no longer run into problems.
