### ISSUE TITLE
Autogenerated migration package violates windows naming system

### ISSUE THREAD

**Issue by vccavalcanti** [fauna-brecht/fauna-schema-migrate#6]
The packaged autogenerated by the migration have the timestamp, for example : migrations/2021-02-11T23:54:02.230Z
This is fine for Linux and Mac users, but this don't work on windows machines, the colon is not an allowed character 
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#file-and-directory-names
The following reserved characters:
< (less than)
> (greater than)
: (colon)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
* (asterisk)

I have a project on git that I can not even checkout on a windows machine
$ git checkout feature/migrationLib
fatal: cannot create directory at 'fauna/migrations/2021-02-11T23:54:02.230Z': Invalid argument

**Comment by fauna-brecht** [comment]
I have pushed changed to the following package and tested it on windows (generate/apply/rollback)
https://www.npmjs.com/package/@fauna-databrecht/staging-fauna-schema-migrate
Which seems to work fine on cmd and cmder.

**Comment by vccavalcanti** [comment]
![image](https://user-images.githubusercontent.com/11865385/109245216-d7073f00-77be-11eb-8139-6023e2c8bc8f.png)
Confirmed it is working with CMD/Powershell and Gitbash in Windows 10 Enterprise x64 build 19042.746

Thanks for the fix
