### ISSUE TITLE
Error when running in github actions

### ISSUE THREAD

**Issue by stefanhar** [fauna-brecht/fauna-schema-migrate#8]
We seem to get an error when running `yarn fauna-schema-migrate apply all` in github actions.

The migrations seems to complete successfully though.

The error message suggests adding some checks and fallbacks to prevent this.
https://github.com/vadimdemedes/ink/#israwmodesupported

![Screenshot 2021-02-16 at 22 42 51](https://user-images.githubusercontent.com/6640435/108131027-90bc2c80-70a8-11eb-9bb6-04742516f0a4.png)

**Comment by fauna-brecht** [comment]
Does it work with the --legacy flag? 
I figured that different environments might struggle with ink which is why I added that.
If it doesn't. I'll take a look next week.

**Comment by stefanhar** [comment]
Yes, it works as expected when the --legacy flag is added.
Thank you, I'll close the issues
![Screenshot 2021-02-20 at 12 05 00](https://user-images.githubusercontent.com/6640435/108594816-0c9dc980-7374-11eb-87c8-fe49c73d0e2c.png)
